"""Initial schema

Revision ID: a1e0592a5845
Revises: 
Create Date: 2026-05-23 15:23:15.258019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'a1e0592a5845'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('identificacion', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificacion')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_cedula'), 'usuarios', ['cedula'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('reglas_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('configuracion_json', sa.JSON(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reglas_trabajo_id'), 'reglas_trabajo', ['id'], unique=False)
    op.create_table('usuarios_clientes',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'cliente_id')
    )
    op.create_table('lotes_procesamiento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('regla_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('operario_id', sa.Integer(), nullable=False),
    sa.Column('modo_ingesta', sa.String(length=50), nullable=False),
    sa.Column('ruta_temporal', sa.String(length=500), nullable=True),
    sa.Column('total_docs', sa.Integer(), nullable=True),
    sa.Column('total_paginas', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['regla_id'], ['reglas_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotes_procesamiento_batch_id'), 'lotes_procesamiento', ['batch_id'], unique=True)
    op.create_table('documentos_lote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=300), nullable=False),
    sa.Column('ruta_original', sa.String(length=500), nullable=True),
    sa.Column('ruta_temporal', sa.String(length=500), nullable=True),
    sa.Column('total_paginas', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('error_detalle', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_procesamiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos_clasificados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('regla_id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('campos_extraidos_json', sa.JSON(), nullable=False),
    sa.Column('ruta_destino_final', sa.String(length=500), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('timestamp_clasificacion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_lote.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_id')
    )
    op.create_index(op.f('ix_documentos_clasificados_batch_id'), 'documentos_clasificados', ['batch_id'], unique=False)
    op.create_index(op.f('ix_documentos_clasificados_cliente_id'), 'documentos_clasificados', ['cliente_id'], unique=False)
    op.create_table('documentos_pendientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('motivo_rechazo', sa.String(length=500), nullable=True),
    sa.Column('campos_extraidos_json', sa.JSON(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('operario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_lote.id'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_id')
    )
    op.create_index(op.f('ix_documentos_pendientes_batch_id'), 'documentos_pendientes', ['batch_id'], unique=False)
    op.create_index(op.f('ix_documentos_pendientes_cliente_id'), 'documentos_pendientes', ['cliente_id'], unique=False)
    op.create_table('log_auditoria_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('detalles', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_lote.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_auditoria_usuario_documento_id'), 'log_auditoria_usuario', ['documento_id'], unique=False)
    op.create_index(op.f('ix_log_auditoria_usuario_usuario_id'), 'log_auditoria_usuario', ['usuario_id'], unique=False)
    op.create_table('log_ia_invocaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.Column('proveedor', sa.String(length=50), nullable=False),
    sa.Column('endpoint_invocado', sa.String(length=200), nullable=True),
    sa.Column('payload_enviado', sa.JSON(), nullable=True),
    sa.Column('respuesta_recibida', sa.JSON(), nullable=True),
    sa.Column('tiempo_respuesta_ms', sa.Integer(), nullable=True),
    sa.Column('exitoso', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_lote.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_ia_invocaciones_documento_id'), 'log_ia_invocaciones', ['documento_id'], unique=False)
    op.create_table('log_proceso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.Column('estado_anterior', sa.String(length=50), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_lote.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_proceso_documento_id'), 'log_proceso', ['documento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_proceso_documento_id'), table_name='log_proceso')
    op.drop_table('log_proceso')
    op.drop_index(op.f('ix_log_ia_invocaciones_documento_id'), table_name='log_ia_invocaciones')
    op.drop_table('log_ia_invocaciones')
    op.drop_index(op.f('ix_log_auditoria_usuario_usuario_id'), table_name='log_auditoria_usuario')
    op.drop_index(op.f('ix_log_auditoria_usuario_documento_id'), table_name='log_auditoria_usuario')
    op.drop_table('log_auditoria_usuario')
    op.drop_index(op.f('ix_documentos_pendientes_cliente_id'), table_name='documentos_pendientes')
    op.drop_index(op.f('ix_documentos_pendientes_batch_id'), table_name='documentos_pendientes')
    op.drop_table('documentos_pendientes')
    op.drop_index(op.f('ix_documentos_clasificados_cliente_id'), table_name='documentos_clasificados')
    op.drop_index(op.f('ix_documentos_clasificados_batch_id'), table_name='documentos_clasificados')
    op.drop_table('documentos_clasificados')
    op.drop_table('documentos_lote')
    op.drop_index(op.f('ix_lotes_procesamiento_batch_id'), table_name='lotes_procesamiento')
    op.drop_table('lotes_procesamiento')
    op.drop_table('usuarios_clientes')
    op.drop_index(op.f('ix_reglas_trabajo_id'), table_name='reglas_trabajo')
    op.drop_table('reglas_trabajo')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cedula'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
